import Head from 'next/head';
import Layout from '@/components/Layout';
import Animated from '@/components/AnimatedText';
import Image from 'next/image';
import Link from 'next/link';
import profilePic from "../../public/vercel.svg";
import { LinkArrow } from '@/components/Icons';

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <main className='flex items-center text-dark w-full min-h-screen dark:text-light'>
                <Layout className='pt-0'>
                    <div className='flex items-center justify-between w-full'>
                        <div className='w-1/2'>
                            <Image src={profilePic} alt="emadak47" className="w-full h-auto" />
                        </div>
                        <div className='w-1/2 flex flex-col items-center self-center'>
                            <Animated text="PlaceHolder" className='!text-6xl !text-left' />
                            <p className='my-4 text-base font-medium'>
                                PlaceHolder
                            </p>
                            <div className='flex items-center self-start mt-2'>
                                <Link
                                    href="/resume.pdf"
                                    target={"_blank"}
                                    className='flex items-center bg-dark text-light p-2.5 px-6 
                                            rounded-lg text-lg font-semibold hover:bg-light hover:text-dark 
                                            border border-solid border-transparent hover:border-dark 
                                            dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light
                                            hover:dark:border-light'
                                >
                                    Resume
                                    <LinkArrow className={"w-6 ml-1"} />
                                </Link>
                                <Link 
                                    href="mailto:emadakhrasidleb@gmail.com" 
                                    target={"_blank"}
                                    className='ml-4 text-lg font-medium capitalize text-dark underline dark:text-light'
                                >
                                    E-mail
                                </Link>
                            </div>
                        </div>
                    </div>
                </Layout>
            </main>
        </>
    );
}
